displayName=Loot Flexer
author=Nares18
description=Screenshots your big drops and shares to your Discord channel to flex on your friends
tags=loot,drop,drops
version=
plugins=com.lootflexer.LootFlexerPlugin
build=standard